### ISSUE TITLE
Generate list of gems for the homepage from gems.yml

### ISSUE THREAD

**Issue by minad** [SciRuby/sciruby#41]
See gems.yml and gems.slim

~~~
slimrb gems.slim > gems.html
~~~

generated file http://minad.github.io/sciruby-gems/

ping @mohawkjohn @agarie

**Comment by audy** [comment]
That's slick. We should put that up on SciRuby.com.

I thought it might be good to add one of those dependency out-of-date badges using Gemnasium as this is a "meta" Gem. But Gemnasium doesn't know how to parse the `gems.yaml`. It might be good to commit an actual `Gemfile`.

**Comment by minad** [comment]
Thx. An actual gemfile is not sufficient since I need additional information as given in gems.yml.

However, what gemnasium does is pretty trivial, I quickly added some checks to gems.slim, see

https://htmlpreview.github.io/?https://github.com/SciRuby/sciruby/blob/master/gems.html

**Comment by minad** [comment]
maybe I just do both. so we can use gemnasium if we want

**Comment by agarie** [comment]
That is definitely a good idea. A REALLY good idea. Having the `sciruby` gem and the sciruby.com website synchronised in this way should help with discovering new libraries and tools.

By the way, that table you created is really neat.

We need to update sciruby.com, put the list of GSoC students in the last years, their projects, etc. :-( The source is in [SciRuby/sciruby.com](https://github.com/SciRuby/sciruby.com). It's been a long time since I last used Jekyll/Octopress, so I'll need some time to make sure I'm not doing anything wrong.

**Comment by audy** [comment]
I always forget how Octopress works and I set up the site :confounded:

**Comment by minad** [comment]
Ok, I want to do the list update automatically via travis. I will write a small deploy script which deploys to some gh-pages and then we can adapt it to the sciruby website.

I hope that this list will also act as some motivation to get all the components work together, e.g. gsl and nmatrix still doesn't work for me.

**Comment by audy** [comment]
I was working on a `.travis.yml` for this but I couldn't get all of the
libraries to install. I thought it would be good to show that the SciRuby
meta-gem can be installed using the methods explained in the documentation.
I also thought it would be beneficial to add an OS X build.

> gsl and nmatrix still doesn't work for me

This might be the problem I was having. I'm working on it over [here](
https://github.com/audy/SciRuby/tree/travis). Commits are currently a mess.
Maybe someone who is more familiar with installing all of these libraries
could have a look.

On Wed, Jun 10, 2015 at 10:51 AM, Daniel Mendler <notifications@github.com>
wrote:

> Ok, I want to do the list update automatically via travis. I will write a
> small deploy script which deploys to some gh-pages and then we can adapt it
> to the sciruby website.
>
> I hope that this list will also act as some motivation to get all the
> components work together, e.g. gsl and nmatrix still doesn't work for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SciRuby/sciruby/issues/41#issuecomment-110782530>.
>



-- 
--austin

**Comment by minad** [comment]
@audy great, I am working on some tests and the next thing will be the travis. You can take a look at sciruby-notebooks/Dockerfile. There the installation already works.

**Comment by agarie** [comment]
I'm pretty sure @v0dro can help you with GSL and NMatrix. He got `gsl-nmatrix` working on travis for Statsample. :+1:

**Comment by minad** [comment]
@audy I pushed a small test suite. If you are still working on travis, you can use that. Do at first the apt-gets, then a bundle install and finally a rake test

**Comment by minad** [comment]
@audy I activated the travis.yml that you provided with slight modifications. In principle this should work

https://travis-ci.org/SciRuby/sciruby

The gem list will be automatically updated at http://minad.github.io/sciruby-gems/

**Comment by v0dro** [comment]
@audy The old gsl-nmatrix gem (https://github.com/SciRuby/rb-gsl) does not compile as of now. it was built using an old nmatrix which is completely different from the current one.

Keeping this in mind I re-forked the narray dependent rb-gsl (https://github.com/blackwinter/rb-gsl) and made a brand new gsl-nmatrix (https://github.com/v0dro/gsl-nmatrix) which works great. It compiles fine and statsample works perfectly with it. [Heres a blog post describing the process](http://v0dro.github.io/blog/2015/05/12/making-statsample-work-with-rb-gsl-and-gsl-nmatrix/).

The only problem with this is that it abandons the commits that were made the SciRuby/rb-gsl gem. Hence, once I get a breather from GSOC I will be merging my fork of gsl-nmatrix with SciRuby/rb-gsl and make my fork the default nmatrix-dependent GSL ruby wrapper.

[The author of rb-gsl ](https://github.com/blackwinter) is also optimistic about an nmatrix dependent GSL wrapper and is willing to replace it with his narray dependent wrapper.

So all in all gsl-nmatrix would be currently unavailable. I will try to do the ASAP, but I'm quite busy with GSOC currently.

If you want to use the gem you can clone it from my repo and compile it. Or you can also write a script to do that so that users of the sciruby meta-gem can take advantage of an nmatrix-dependent GSL wrapper.

**Comment by minad** [comment]
@v0dro as long as rb-gsl doesn't compile cleanly with nmatrix as a gem we cannot include it in the dependencies. It is excluded in gems.yml for now.

**Comment by mohawkjohn** [comment]
@agarie @minad @audy You want to clone sciruby.com, do `git checkout source`, and work in that branch, generally. `master` contains the raw Octopress sources, but `source` is where we keep SciRuby-specific stuff. =)

**Comment by minad** [comment]
The script https://github.com/SciRuby/sciruby/blob/master/scripts/deploy deploys the page automatically to http://minad.github.io/sciruby-gems/

I think we can do the same with the website.
